/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepapersRouteImport } from './routes/whitepapers'
import { Route as TwinEngineRouteImport } from './routes/twin-engine'
import { Route as TrainingLedgerRouteImport } from './routes/training-ledger'
import { Route as ThreatProfilesRouteImport } from './routes/threat-profiles'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as S4TalkRouteImport } from './routes/s4-talk'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FieldReportsRouteImport } from './routes/field-reports'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DefConBriefRouteImport } from './routes/def-con-brief'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CaseFilesRouteImport } from './routes/case-files'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreatProfilesIdRouteImport } from './routes/threat-profiles.$id'
import { Route as LeaderboardSubmitRouteImport } from './routes/leaderboard/submit'
import { Route as FacilityIdRouteImport } from './routes/facility.$id'
import { Route as CaseFilesIdRouteImport } from './routes/case-files.$id'

const WhitepapersRoute = WhitepapersRouteImport.update({
  id: '/whitepapers',
  path: '/whitepapers',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinEngineRoute = TwinEngineRouteImport.update({
  id: '/twin-engine',
  path: '/twin-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingLedgerRoute = TrainingLedgerRouteImport.update({
  id: '/training-ledger',
  path: '/training-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatProfilesRoute = ThreatProfilesRouteImport.update({
  id: '/threat-profiles',
  path: '/threat-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const S4TalkRoute = S4TalkRouteImport.update({
  id: '/s4-talk',
  path: '/s4-talk',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldReportsRoute = FieldReportsRouteImport.update({
  id: '/field-reports',
  path: '/field-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DefConBriefRoute = DefConBriefRouteImport.update({
  id: '/def-con-brief',
  path: '/def-con-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseFilesRoute = CaseFilesRouteImport.update({
  id: '/case-files',
  path: '/case-files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatProfilesIdRoute = ThreatProfilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThreatProfilesRoute,
} as any)
const LeaderboardSubmitRoute = LeaderboardSubmitRouteImport.update({
  id: '/leaderboard/submit',
  path: '/leaderboard/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityIdRoute = FacilityIdRouteImport.update({
  id: '/facility/$id',
  path: '/facility/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseFilesIdRoute = CaseFilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CaseFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-files': typeof CaseFilesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/def-con-brief': typeof DefConBriefRoute
  '/faq': typeof FaqRoute
  '/field-reports': typeof FieldReportsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/s4-talk': typeof S4TalkRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/terms': typeof TermsRoute
  '/threat-profiles': typeof ThreatProfilesRouteWithChildren
  '/training-ledger': typeof TrainingLedgerRoute
  '/twin-engine': typeof TwinEngineRoute
  '/whitepapers': typeof WhitepapersRoute
  '/case-files/$id': typeof CaseFilesIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/leaderboard/submit': typeof LeaderboardSubmitRoute
  '/threat-profiles/$id': typeof ThreatProfilesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-files': typeof CaseFilesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/def-con-brief': typeof DefConBriefRoute
  '/faq': typeof FaqRoute
  '/field-reports': typeof FieldReportsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/s4-talk': typeof S4TalkRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/terms': typeof TermsRoute
  '/threat-profiles': typeof ThreatProfilesRouteWithChildren
  '/training-ledger': typeof TrainingLedgerRoute
  '/twin-engine': typeof TwinEngineRoute
  '/whitepapers': typeof WhitepapersRoute
  '/case-files/$id': typeof CaseFilesIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/leaderboard/submit': typeof LeaderboardSubmitRoute
  '/threat-profiles/$id': typeof ThreatProfilesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-files': typeof CaseFilesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/def-con-brief': typeof DefConBriefRoute
  '/faq': typeof FaqRoute
  '/field-reports': typeof FieldReportsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/s4-talk': typeof S4TalkRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/terms': typeof TermsRoute
  '/threat-profiles': typeof ThreatProfilesRouteWithChildren
  '/training-ledger': typeof TrainingLedgerRoute
  '/twin-engine': typeof TwinEngineRoute
  '/whitepapers': typeof WhitepapersRoute
  '/case-files/$id': typeof CaseFilesIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/leaderboard/submit': typeof LeaderboardSubmitRoute
  '/threat-profiles/$id': typeof ThreatProfilesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/case-files'
    | '/dashboard'
    | '/def-con-brief'
    | '/faq'
    | '/field-reports'
    | '/login'
    | '/privacy'
    | '/s4-talk'
    | '/signup'
    | '/simulation'
    | '/terms'
    | '/threat-profiles'
    | '/training-ledger'
    | '/twin-engine'
    | '/whitepapers'
    | '/case-files/$id'
    | '/facility/$id'
    | '/leaderboard/submit'
    | '/threat-profiles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/case-files'
    | '/dashboard'
    | '/def-con-brief'
    | '/faq'
    | '/field-reports'
    | '/login'
    | '/privacy'
    | '/s4-talk'
    | '/signup'
    | '/simulation'
    | '/terms'
    | '/threat-profiles'
    | '/training-ledger'
    | '/twin-engine'
    | '/whitepapers'
    | '/case-files/$id'
    | '/facility/$id'
    | '/leaderboard/submit'
    | '/threat-profiles/$id'
  id:
    | '__root__'
    | '/'
    | '/case-files'
    | '/dashboard'
    | '/def-con-brief'
    | '/faq'
    | '/field-reports'
    | '/login'
    | '/privacy'
    | '/s4-talk'
    | '/signup'
    | '/simulation'
    | '/terms'
    | '/threat-profiles'
    | '/training-ledger'
    | '/twin-engine'
    | '/whitepapers'
    | '/case-files/$id'
    | '/facility/$id'
    | '/leaderboard/submit'
    | '/threat-profiles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseFilesRoute: typeof CaseFilesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DefConBriefRoute: typeof DefConBriefRoute
  FaqRoute: typeof FaqRoute
  FieldReportsRoute: typeof FieldReportsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  S4TalkRoute: typeof S4TalkRoute
  SignupRoute: typeof SignupRoute
  SimulationRoute: typeof SimulationRoute
  TermsRoute: typeof TermsRoute
  ThreatProfilesRoute: typeof ThreatProfilesRouteWithChildren
  TrainingLedgerRoute: typeof TrainingLedgerRoute
  TwinEngineRoute: typeof TwinEngineRoute
  WhitepapersRoute: typeof WhitepapersRoute
  FacilityIdRoute: typeof FacilityIdRoute
  LeaderboardSubmitRoute: typeof LeaderboardSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepapers': {
      id: '/whitepapers'
      path: '/whitepapers'
      fullPath: '/whitepapers'
      preLoaderRoute: typeof WhitepapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin-engine': {
      id: '/twin-engine'
      path: '/twin-engine'
      fullPath: '/twin-engine'
      preLoaderRoute: typeof TwinEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-ledger': {
      id: '/training-ledger'
      path: '/training-ledger'
      fullPath: '/training-ledger'
      preLoaderRoute: typeof TrainingLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-profiles': {
      id: '/threat-profiles'
      path: '/threat-profiles'
      fullPath: '/threat-profiles'
      preLoaderRoute: typeof ThreatProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s4-talk': {
      id: '/s4-talk'
      path: '/s4-talk'
      fullPath: '/s4-talk'
      preLoaderRoute: typeof S4TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-reports': {
      id: '/field-reports'
      path: '/field-reports'
      fullPath: '/field-reports'
      preLoaderRoute: typeof FieldReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/def-con-brief': {
      id: '/def-con-brief'
      path: '/def-con-brief'
      fullPath: '/def-con-brief'
      preLoaderRoute: typeof DefConBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-files': {
      id: '/case-files'
      path: '/case-files'
      fullPath: '/case-files'
      preLoaderRoute: typeof CaseFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-profiles/$id': {
      id: '/threat-profiles/$id'
      path: '/$id'
      fullPath: '/threat-profiles/$id'
      preLoaderRoute: typeof ThreatProfilesIdRouteImport
      parentRoute: typeof ThreatProfilesRoute
    }
    '/leaderboard/submit': {
      id: '/leaderboard/submit'
      path: '/leaderboard/submit'
      fullPath: '/leaderboard/submit'
      preLoaderRoute: typeof LeaderboardSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/$id': {
      id: '/facility/$id'
      path: '/facility/$id'
      fullPath: '/facility/$id'
      preLoaderRoute: typeof FacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-files/$id': {
      id: '/case-files/$id'
      path: '/$id'
      fullPath: '/case-files/$id'
      preLoaderRoute: typeof CaseFilesIdRouteImport
      parentRoute: typeof CaseFilesRoute
    }
  }
}

interface CaseFilesRouteChildren {
  CaseFilesIdRoute: typeof CaseFilesIdRoute
}

const CaseFilesRouteChildren: CaseFilesRouteChildren = {
  CaseFilesIdRoute: CaseFilesIdRoute,
}

const CaseFilesRouteWithChildren = CaseFilesRoute._addFileChildren(
  CaseFilesRouteChildren,
)

interface ThreatProfilesRouteChildren {
  ThreatProfilesIdRoute: typeof ThreatProfilesIdRoute
}

const ThreatProfilesRouteChildren: ThreatProfilesRouteChildren = {
  ThreatProfilesIdRoute: ThreatProfilesIdRoute,
}

const ThreatProfilesRouteWithChildren = ThreatProfilesRoute._addFileChildren(
  ThreatProfilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseFilesRoute: CaseFilesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DefConBriefRoute: DefConBriefRoute,
  FaqRoute: FaqRoute,
  FieldReportsRoute: FieldReportsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  S4TalkRoute: S4TalkRoute,
  SignupRoute: SignupRoute,
  SimulationRoute: SimulationRoute,
  TermsRoute: TermsRoute,
  ThreatProfilesRoute: ThreatProfilesRouteWithChildren,
  TrainingLedgerRoute: TrainingLedgerRoute,
  TwinEngineRoute: TwinEngineRoute,
  WhitepapersRoute: WhitepapersRoute,
  FacilityIdRoute: FacilityIdRoute,
  LeaderboardSubmitRoute: LeaderboardSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
